[tool.poetry]
name = "api-library"
version = "0.1.0"
description = ""
authors = ["Jorge Vasconcelos"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {version = "*", extras = ["standard"]}
uvicorn = "*"
python-dotenv = "*"
SQLAlchemy = "*"
SQLAlchemy-serializer = "*"
python-multipart = "*"
pycryptodome = "*"
redis = "*"
alembic = "*"
opentelemetry-distro = "*"
opentelemetry-exporter-otlp = "*"
opentelemetry-instrumentation-logging = "*"
pydantic = "*"
pypika = "*"
psycopg2-binary = "2.9.10"
gunicorn = "*"
pwdlib = {extras = ["argon2"], version = "*"}
pyjwt = "*"
starlette-admin = "*"


[tool.poetry.group.dev.dependencies]
Faker = "*"
pytest = "*"
httpx = "*"
ruff = "*"
allure-pytest = "*"
locust = "*"

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "A",
    "B",
    "C",
    # "D",
    "E",
    "F",
    "I", # isort


]
ignore = [
    "SIM102",
    "RUF013"
]

fixable = ["A", "B", "C", "D", "E", "F", "I", "F401", "UP007"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"


[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
