server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317  # Explicitly set the gRPC port
        http:
          endpoint: 0.0.0.0:4318  # Explicitly set the HTTP port

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo
