receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  prometheus:
    endpoint: 0.0.0.0:1234

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      exporters: [loki]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]